"""add value_text to user_step_metrics

Revision ID: 6bf898438ea6
Revises: d621fa5f7431
Create Date: 2026-03-05 02:09:16.769918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf898438ea6'
down_revision: Union[str, Sequence[str], None] = 'd621fa5f7431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.add_column('user_step_metrics', sa.Column('value_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_step_metrics', 'value_text')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    # ### end Alembic commands ###
