"""delete from  entries

Revision ID: 8e6f00314707
Revises: a38db7bd67dd
Create Date: 2026-02-14 21:56:51.593042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6f00314707'
down_revision: Union[str, Sequence[str], None] = 'a38db7bd67dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.alter_column('entries', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
